export * from "./CastCrew";
export * from "./Genres";
export * from "./Home";
export * from "./Login";
export * from "./MovieDetails";
export * from "./Movies";
export * from "./SelectSeats";
export * from "./SelectTime";
export * from "./Ticket";
