POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "default@gmail.com",
    "password": "1234567890"
}


# POST http://localhost:3000/auth/register
# Content-Type: application/json

# {
#     "email": "default@gmail.com",
#     "password": "1234567890"
# }